package: respondo
version: '0.0.1-dev-2024-04-07'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/respondo


requires:
    php:
        version: '>8.1,<9'
    redaxo: ^5.17
    packages:
        yform: "^4"
        yform_spam_protection: "^1"



page:
    title: translate:respondo_title
    block: system
    prio: 20
    icon: rex-icon fa-comments

pages:
    moderation:
        title: translate:respondo_table_moderation
        icon: rex-icon fa-hourglass-half
        perm: respondo[]
    spam:
        title: translate:respondo_table_spam
        icon: rex-icon fa-ban
        perm: respondo[guestbook]
    article:
        title: translate:respondo_table_article
        icon: rex-icon fa-file-text
        perm: respondo[article]
    yform_table:
        title: translate:respondo_table_yform_table
        icon: rex-icon fa-table
        perm: respondo[yform_table]
    comment:
        title: translate:respondo_table_comment
        icon: rex-icon fa-comment
        perm: respondo[table]
    guestbook:
        title: translate:respondo_table_guestbook
        icon: rex-icon fa-book
        perm: respondo[guestbook]
    all:
        title: translate:respondo_table_all
        icon: rex-icon fa-comments
        perm: respondo[all]
    settings:
        title: translate:respondo_settings
        icon: rex-icon fa-gear
        itemclass: pull-right
        perm: admin
    docs:
        title: translate:respondo_docs
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: respondo[docs]

default_config:
    editor: 'form-control redactor-editor--default'

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
